name: Build, test, lint in conda environment

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env create -n yoke_test_env python=3.9 flit
        conda activate yoke_test_env
        export PYTHONUSERBASE=$CONDA_PREFIX
        flit install --user --symlink --deps=all
    - name: Test with pytest
      run: |
        pytest -v --junitxml=report.xml --cov=yoke -Werror
